# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# this file should be run in the root of the repo
services:
  feedbackmanagement-mongo-server:
    build:
      dockerfile: comps/feedback_management/mongo/Dockerfile
    image: ${REGISTRY:-opea}/feedbackmanagement-mongo-server:${TAG:-latest}
  feedbackmanagement-arango-server:
    build:
      dockerfile: comps/feedback_management/arango/Dockerfile
    image: ${REGISTRY:-opea}/feedbackmanagement-arango-server:${TAG:-latest}